/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CredentialRegistry {
  export type CredentialStruct = {
    id: BigNumberish;
    credentialType: string;
    description: string;
    issuerName: string;
    issuerAddress: AddressLike;
    timestamp: BigNumberish;
    isValid: boolean;
  };

  export type CredentialStructOutput = [
    id: bigint,
    credentialType: string,
    description: string,
    issuerName: string,
    issuerAddress: string,
    timestamp: bigint,
    isValid: boolean
  ] & {
    id: bigint;
    credentialType: string;
    description: string;
    issuerName: string;
    issuerAddress: string;
    timestamp: bigint;
    isValid: boolean;
  };
}

export interface CredentialRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addIssuer"
      | "authorizedIssuers"
      | "credentials"
      | "getCredentialCount"
      | "getCredentials"
      | "issueCredential"
      | "owner"
      | "removeIssuer"
      | "revokeCredential"
      | "verifyCredential"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CredentialIssued"
      | "CredentialRevoked"
      | "IssuerAdded"
      | "IssuerRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedIssuers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "credentials",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredentialCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredentials",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCredential",
    values: [AddressLike, string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCredential",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addIssuer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "credentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredentialCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCredential",
    data: BytesLike
  ): Result;
}

export namespace CredentialIssuedEvent {
  export type InputTuple = [
    freelancer: AddressLike,
    credentialId: BigNumberish,
    credentialType: string,
    issuerName: string,
    issuerAddress: AddressLike
  ];
  export type OutputTuple = [
    freelancer: string,
    credentialId: bigint,
    credentialType: string,
    issuerName: string,
    issuerAddress: string
  ];
  export interface OutputObject {
    freelancer: string;
    credentialId: bigint;
    credentialType: string;
    issuerName: string;
    issuerAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [
    freelancer: AddressLike,
    credentialId: BigNumberish
  ];
  export type OutputTuple = [freelancer: string, credentialId: bigint];
  export interface OutputObject {
    freelancer: string;
    credentialId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerAddedEvent {
  export type InputTuple = [issuer: AddressLike];
  export type OutputTuple = [issuer: string];
  export interface OutputObject {
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerRemovedEvent {
  export type InputTuple = [issuer: AddressLike];
  export type OutputTuple = [issuer: string];
  export interface OutputObject {
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CredentialRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CredentialRegistry;
  waitForDeployment(): Promise<this>;

  interface: CredentialRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addIssuer: TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;

  authorizedIssuers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  credentials: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, string, string, string, bigint, boolean] & {
        id: bigint;
        credentialType: string;
        description: string;
        issuerName: string;
        issuerAddress: string;
        timestamp: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;

  getCredentialCount: TypedContractMethod<
    [freelancer: AddressLike],
    [bigint],
    "view"
  >;

  getCredentials: TypedContractMethod<
    [freelancer: AddressLike],
    [CredentialRegistry.CredentialStructOutput[]],
    "view"
  >;

  issueCredential: TypedContractMethod<
    [
      freelancer: AddressLike,
      credentialType: string,
      description: string,
      issuerName: string
    ],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeCredential: TypedContractMethod<
    [freelancer: AddressLike, credentialId: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyCredential: TypedContractMethod<
    [freelancer: AddressLike, credentialId: BigNumberish],
    [
      [boolean, CredentialRegistry.CredentialStructOutput] & {
        isValid: boolean;
        credential: CredentialRegistry.CredentialStructOutput;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedIssuers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "credentials"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, string, string, string, bigint, boolean] & {
        id: bigint;
        credentialType: string;
        description: string;
        issuerName: string;
        issuerAddress: string;
        timestamp: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCredentialCount"
  ): TypedContractMethod<[freelancer: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCredentials"
  ): TypedContractMethod<
    [freelancer: AddressLike],
    [CredentialRegistry.CredentialStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueCredential"
  ): TypedContractMethod<
    [
      freelancer: AddressLike,
      credentialType: string,
      description: string,
      issuerName: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeCredential"
  ): TypedContractMethod<
    [freelancer: AddressLike, credentialId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyCredential"
  ): TypedContractMethod<
    [freelancer: AddressLike, credentialId: BigNumberish],
    [
      [boolean, CredentialRegistry.CredentialStructOutput] & {
        isValid: boolean;
        credential: CredentialRegistry.CredentialStructOutput;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CredentialIssued"
  ): TypedContractEvent<
    CredentialIssuedEvent.InputTuple,
    CredentialIssuedEvent.OutputTuple,
    CredentialIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerAdded"
  ): TypedContractEvent<
    IssuerAddedEvent.InputTuple,
    IssuerAddedEvent.OutputTuple,
    IssuerAddedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerRemoved"
  ): TypedContractEvent<
    IssuerRemovedEvent.InputTuple,
    IssuerRemovedEvent.OutputTuple,
    IssuerRemovedEvent.OutputObject
  >;

  filters: {
    "CredentialIssued(address,uint256,string,string,address)": TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;
    CredentialIssued: TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;

    "CredentialRevoked(address,uint256)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;

    "IssuerAdded(address)": TypedContractEvent<
      IssuerAddedEvent.InputTuple,
      IssuerAddedEvent.OutputTuple,
      IssuerAddedEvent.OutputObject
    >;
    IssuerAdded: TypedContractEvent<
      IssuerAddedEvent.InputTuple,
      IssuerAddedEvent.OutputTuple,
      IssuerAddedEvent.OutputObject
    >;

    "IssuerRemoved(address)": TypedContractEvent<
      IssuerRemovedEvent.InputTuple,
      IssuerRemovedEvent.OutputTuple,
      IssuerRemovedEvent.OutputObject
    >;
    IssuerRemoved: TypedContractEvent<
      IssuerRemovedEvent.InputTuple,
      IssuerRemovedEvent.OutputTuple,
      IssuerRemovedEvent.OutputObject
    >;
  };
}
