/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace MonadWorkEscrow {
  export type JobStruct = {
    employer: AddressLike;
    freelancer: AddressLike;
    ratePerSecond: BigNumberish;
    totalDeposit: BigNumberish;
    streamStartTime: BigNumberish;
    accumulatedEarned: BigNumberish;
    totalWithdrawn: BigNumberish;
    status: BigNumberish;
    description: string;
    streamActive: boolean;
  };

  export type JobStructOutput = [
    employer: string,
    freelancer: string,
    ratePerSecond: bigint,
    totalDeposit: bigint,
    streamStartTime: bigint,
    accumulatedEarned: bigint,
    totalWithdrawn: bigint,
    status: bigint,
    description: string,
    streamActive: boolean
  ] & {
    employer: string;
    freelancer: string;
    ratePerSecond: bigint;
    totalDeposit: bigint;
    streamStartTime: bigint;
    accumulatedEarned: bigint;
    totalWithdrawn: bigint;
    status: bigint;
    description: string;
    streamActive: boolean;
  };
}

export interface MonadWorkEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptJob"
      | "approve"
      | "arbitrator"
      | "cancel"
      | "createJob"
      | "dispute"
      | "getEarnedAmount"
      | "getJob"
      | "jobCount"
      | "jobs"
      | "owner"
      | "pauseStream"
      | "resolve"
      | "resumeStream"
      | "setArbitrator"
      | "startStream"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeRaised"
      | "DisputeResolved"
      | "JobAccepted"
      | "JobApproved"
      | "JobCancelled"
      | "JobCreated"
      | "StreamPaused"
      | "StreamResumed"
      | "StreamStarted"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "arbitrator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "dispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEarnedAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "jobCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "jobs", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseStream",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolve",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resumeStream",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setArbitrator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startStream",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "acceptJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "arbitrator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dispute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEarnedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resumeStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setArbitrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [jobId: BigNumberish, raisedBy: AddressLike];
  export type OutputTuple = [jobId: bigint, raisedBy: string];
  export interface OutputObject {
    jobId: bigint;
    raisedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    freelancerPercent: BigNumberish,
    employerPercent: BigNumberish,
    freelancerAmount: BigNumberish,
    employerAmount: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    freelancerPercent: bigint,
    employerPercent: bigint,
    freelancerAmount: bigint,
    employerAmount: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    freelancerPercent: bigint;
    employerPercent: bigint;
    freelancerAmount: bigint;
    employerAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobAcceptedEvent {
  export type InputTuple = [jobId: BigNumberish, freelancer: AddressLike];
  export type OutputTuple = [jobId: bigint, freelancer: string];
  export interface OutputObject {
    jobId: bigint;
    freelancer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobApprovedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    freelancerPayout: BigNumberish,
    employerRefund: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    freelancerPayout: bigint,
    employerRefund: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    freelancerPayout: bigint;
    employerRefund: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCancelledEvent {
  export type InputTuple = [jobId: BigNumberish, refundAmount: BigNumberish];
  export type OutputTuple = [jobId: bigint, refundAmount: bigint];
  export interface OutputObject {
    jobId: bigint;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    employer: AddressLike,
    freelancer: AddressLike,
    ratePerSecond: BigNumberish,
    totalDeposit: BigNumberish,
    description: string
  ];
  export type OutputTuple = [
    jobId: bigint,
    employer: string,
    freelancer: string,
    ratePerSecond: bigint,
    totalDeposit: bigint,
    description: string
  ];
  export interface OutputObject {
    jobId: bigint;
    employer: string;
    freelancer: string;
    ratePerSecond: bigint;
    totalDeposit: bigint;
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamPausedEvent {
  export type InputTuple = [jobId: BigNumberish, earnedSoFar: BigNumberish];
  export type OutputTuple = [jobId: bigint, earnedSoFar: bigint];
  export interface OutputObject {
    jobId: bigint;
    earnedSoFar: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamResumedEvent {
  export type InputTuple = [jobId: BigNumberish, resumeTime: BigNumberish];
  export type OutputTuple = [jobId: bigint, resumeTime: bigint];
  export interface OutputObject {
    jobId: bigint;
    resumeTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamStartedEvent {
  export type InputTuple = [jobId: BigNumberish, startTime: BigNumberish];
  export type OutputTuple = [jobId: bigint, startTime: bigint];
  export interface OutputObject {
    jobId: bigint;
    startTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    freelancer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [jobId: bigint, freelancer: string, amount: bigint];
  export interface OutputObject {
    jobId: bigint;
    freelancer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MonadWorkEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): MonadWorkEscrow;
  waitForDeployment(): Promise<this>;

  interface: MonadWorkEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  approve: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  arbitrator: TypedContractMethod<[], [string], "view">;

  cancel: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  createJob: TypedContractMethod<
    [freelancer: AddressLike, ratePerSecond: BigNumberish, description: string],
    [bigint],
    "payable"
  >;

  dispute: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  getEarnedAmount: TypedContractMethod<[jobId: BigNumberish], [bigint], "view">;

  getJob: TypedContractMethod<
    [jobId: BigNumberish],
    [MonadWorkEscrow.JobStructOutput],
    "view"
  >;

  jobCount: TypedContractMethod<[], [bigint], "view">;

  jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean
      ] & {
        employer: string;
        freelancer: string;
        ratePerSecond: bigint;
        totalDeposit: bigint;
        streamStartTime: bigint;
        accumulatedEarned: bigint;
        totalWithdrawn: bigint;
        status: bigint;
        description: string;
        streamActive: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pauseStream: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  resolve: TypedContractMethod<
    [
      jobId: BigNumberish,
      freelancerPercent: BigNumberish,
      employerPercent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  resumeStream: TypedContractMethod<
    [jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setArbitrator: TypedContractMethod<
    [_arbitrator: AddressLike],
    [void],
    "nonpayable"
  >;

  startStream: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  withdraw: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "arbitrator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<
    [freelancer: AddressLike, ratePerSecond: BigNumberish, description: string],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "dispute"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEarnedAmount"
  ): TypedContractMethod<[jobId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [MonadWorkEscrow.JobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean
      ] & {
        employer: string;
        freelancer: string;
        ratePerSecond: bigint;
        totalDeposit: bigint;
        streamStartTime: bigint;
        accumulatedEarned: bigint;
        totalWithdrawn: bigint;
        status: bigint;
        description: string;
        streamActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pauseStream"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolve"
  ): TypedContractMethod<
    [
      jobId: BigNumberish,
      freelancerPercent: BigNumberish,
      employerPercent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resumeStream"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setArbitrator"
  ): TypedContractMethod<[_arbitrator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startStream"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "JobAccepted"
  ): TypedContractEvent<
    JobAcceptedEvent.InputTuple,
    JobAcceptedEvent.OutputTuple,
    JobAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "JobApproved"
  ): TypedContractEvent<
    JobApprovedEvent.InputTuple,
    JobApprovedEvent.OutputTuple,
    JobApprovedEvent.OutputObject
  >;
  getEvent(
    key: "JobCancelled"
  ): TypedContractEvent<
    JobCancelledEvent.InputTuple,
    JobCancelledEvent.OutputTuple,
    JobCancelledEvent.OutputObject
  >;
  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;
  getEvent(
    key: "StreamPaused"
  ): TypedContractEvent<
    StreamPausedEvent.InputTuple,
    StreamPausedEvent.OutputTuple,
    StreamPausedEvent.OutputObject
  >;
  getEvent(
    key: "StreamResumed"
  ): TypedContractEvent<
    StreamResumedEvent.InputTuple,
    StreamResumedEvent.OutputTuple,
    StreamResumedEvent.OutputObject
  >;
  getEvent(
    key: "StreamStarted"
  ): TypedContractEvent<
    StreamStartedEvent.InputTuple,
    StreamStartedEvent.OutputTuple,
    StreamStartedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "DisputeRaised(uint256,address)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "JobAccepted(uint256,address)": TypedContractEvent<
      JobAcceptedEvent.InputTuple,
      JobAcceptedEvent.OutputTuple,
      JobAcceptedEvent.OutputObject
    >;
    JobAccepted: TypedContractEvent<
      JobAcceptedEvent.InputTuple,
      JobAcceptedEvent.OutputTuple,
      JobAcceptedEvent.OutputObject
    >;

    "JobApproved(uint256,uint256,uint256)": TypedContractEvent<
      JobApprovedEvent.InputTuple,
      JobApprovedEvent.OutputTuple,
      JobApprovedEvent.OutputObject
    >;
    JobApproved: TypedContractEvent<
      JobApprovedEvent.InputTuple,
      JobApprovedEvent.OutputTuple,
      JobApprovedEvent.OutputObject
    >;

    "JobCancelled(uint256,uint256)": TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;
    JobCancelled: TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;

    "JobCreated(uint256,address,address,uint256,uint256,string)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;

    "StreamPaused(uint256,uint256)": TypedContractEvent<
      StreamPausedEvent.InputTuple,
      StreamPausedEvent.OutputTuple,
      StreamPausedEvent.OutputObject
    >;
    StreamPaused: TypedContractEvent<
      StreamPausedEvent.InputTuple,
      StreamPausedEvent.OutputTuple,
      StreamPausedEvent.OutputObject
    >;

    "StreamResumed(uint256,uint256)": TypedContractEvent<
      StreamResumedEvent.InputTuple,
      StreamResumedEvent.OutputTuple,
      StreamResumedEvent.OutputObject
    >;
    StreamResumed: TypedContractEvent<
      StreamResumedEvent.InputTuple,
      StreamResumedEvent.OutputTuple,
      StreamResumedEvent.OutputObject
    >;

    "StreamStarted(uint256,uint256)": TypedContractEvent<
      StreamStartedEvent.InputTuple,
      StreamStartedEvent.OutputTuple,
      StreamStartedEvent.OutputObject
    >;
    StreamStarted: TypedContractEvent<
      StreamStartedEvent.InputTuple,
      StreamStartedEvent.OutputTuple,
      StreamStartedEvent.OutputObject
    >;

    "Withdrawn(uint256,address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
